export { default as aecesLogo } from "./aeces-logo.svg?override";
export { default as eyeShield } from "./eye-shield.svg?override";
export { default as modelOne } from "./model-1.svg?override";
export { default as modelTwo } from "./model-2.svg?override";
export { default as reasonOne } from "./reason-1.svg?override";
export { default as reasonTwo } from "./reason-2.svg?override";
export { default as reasonThree } from "./reason-3.svg?override";
export { default as reasonFour } from "./reason-4.svg?override";
export { default as unizikLogo } from "./unizik-logo.svg?override";
